### PR TITLE
Update guide to use Open Liberty stack

### PR DESCRIPTION
**Pull request by awisniew90**
With the new Open Liberty stack available for use, we want to move this guide over to using that default stack. This required some significant changes, but I'm hoping I preserved the main content and intent of this guide. Let me know if anything is missing or left out. 

Some things to note with these changes:

1. The guide is now using the default Open Liberty stack in appsody hub (rather than the custom stack here: https://github.com/gcharters/stacks/tree/master/experimental/java-microprofile-dev-mode)

2. Since we are no longer using a custom stack, the "Collection Scenario" section is expanded to show how to clone the default Open Liberty stack and customize from there. 

3. Codewind metrics does not work with the Open Liberty stack. Codewind populates these metrics using the `javametrics-dash` endpoint which the OL stack does not user. Once codewind moves to use the `/metrics` endpoint (near future) this will work. For now, the metrics / load testing sections of this guide are commented out.

4. The "Collection Scenario 1" section originally walked through how to update the OL runtime version for the stack. The OL stack has a strict "quarterly" release requirement due to how our OL docker images are tagged in docker hub. Because of this, I removed the runtime version update scenario and simplified this to making a change to the stack version. 

5. For "Collection Scenario 2", since we are no longer using a pre-built stack to work off of, we need to have the user create the psqldb template. I added this template to the guide project in github where a user can use `svn checkout` to pull that down. The links for this are in my own fork/branch, so these links need to be updated before merging.

6. The workshop_setup.sh script is still used for prereq checking, but no longer needed for caching/creating the custom stack/images.

### CODE REVIEW

**Comment by scottkurz** [comment]
So we're taking for granted that this URL is "out there", referenced, in-use and so it's worth updating with a PR into @gcharters' repo.   If this isn't the case, though, we should just take ownership at a new URL.   Graham,  @yeekangc  what do you think?

**Comment by awisniew90** [comment]
I pushed these changes to my fork here: https://github.com/awisniew90/kabanero-dev-getting-started. We can use that repo as the "open liberty stack" version of this guide for the time being.

**Comment by yeekangc** [comment]
Thanks.  We should consider having this under OpenLiberty or somewhere under Appsody as the master copy.

**Comment by awisniew90** [comment]
We could consider adding this to the openliberty stack content. @scottkurz what do you think about that?

**Pull request closed without merging**
